name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - docker_timezone_Tagtesting

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    env:
      TZ: 'Asia/Kolkata'
      TIMESTAMP: ${{ steps.set_timestamp.outputs.timestamp }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Set timestamp
        id: set_timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: ./dockerfile  # Adjust the path to your Dockerfile if necessary
          push: true
          tags: |
            ansumansing/docker-project:latest
            ansumansing/docker-project:${{ github.actor }}-${{ github.sha }}
            ansumansing/docker-project:${{ github.actor }}-${{ env.TIMESTAMP }}

      - name: Extract Docker image digest
        run: echo "Docker image digest - ${{ steps.docker_build.outputs.digest }}"
