name: Build, Analyze, and Push Docker image

on:
  push:
    branches:
      - Kubernetes_Docker
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  codeql_analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          # Use a GitHub token with appropriate permissions
          token: ${{ secrets.TOKEN_GITHUB }}
          languages: 'java'

      - name: Build Docker image
        id: build_image
        run: |
          DOCKER_TAG="latestv${{ needs.codeql_analysis.outputs.random_number }}"
          docker build -t ansumansing/automation-project:${DOCKER_TAG} .
          echo "::set-output name=image_tag::${DOCKER_TAG}"
      - name: Push Docker image
        run: |
          docker push ansumansing/automation-project:${{ steps.build_image.outputs.image_tag }}

  # Add any other jobs or steps as needed
