name: Build, Analyze, and Push Docker image

on:
  push:
    branches:
      - Kubernetes_Docker
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push_docker_image:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # CodeQL Scan Section
      - name: CodeQL Scan
        runs-on: ubuntu-latest
        timeout-minutes: 360
        permissions:
          security-events: write
          actions: read
          contents: read

        strategy:
          fail-fast: false
          matrix:
            language: [ 'java-kotlin' ]

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Initialize CodeQL
            uses: github/codeql-action/init@v3
            with:
              languages: ${{ matrix.language }}

          - name: Autobuild
            uses: github/codeql-action/autobuild@v3

          - name: Perform CodeQL Analysis
            uses: github/codeql-action/analyze@v3
            with:
              category: "/language:${{matrix.language}}"

      # Maven Project Clean, Compile, Docker Login, Build, and Push Section
      - name: Maven Project Clean, Compile, Docker Login, Build, and Push
        run: |
          mvn clean compile &&
          docker/setup-buildx-action@v1 &&
          docker/login-action@v2 \
            username: ${{ secrets.DOCKERHUB_USERNAME }} \
            password: ${{ secrets.DOCKERHUB_TOKEN }} &&
          DOCKER_TAG="latestv${{ needs.codeql_analysis.outputs.random_number }}" &&
          docker build -t ansumansing/automation-project:${DOCKER_TAG} . &&
          echo "::set-output name=image_tag::${DOCKER_TAG}" &&
          docker push ansumansing/automation-project:${DOCKER_TAG}
