name: Build and Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_publish:
    name: Build & push Docker image
    runs-on: ubuntu-latest

    outputs:
      id: random_tag
      value: ${{ steps.generate_random_number.outputs.random_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Random Number
        id: generate_random_number
        run: echo "::set-output name=random_number::$(shuf -i 0-9 -n 1)"

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          languages: java

      - name: Run CodeQL Analysis
        id: codeql
        uses: github/codeql-action/analyze@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          languages: java
          category: "security-and-quality"
          fail-on-results: true
          verbosity: 'debug'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        id: build_image
        run: |
          DOCKER_TAG="latest-V${{ steps.generate_random_number.outputs.random_number }}"
          docker build -t ansumansing/automation-project:${DOCKER_TAG} .
          echo "::set-output name=image_tag::${DOCKER_TAG}"

      - name: Push Docker image
        run: |
          docker push ansumansing/automation-project:${{ steps.build_image.outputs.image_tag }}
