name: Publish Docker image

on:
  push:
    branches: ['newDockerBuild'] 

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build with Maven
        run: mvn -B clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: DockerFileFolder/dockerfile  # Adjust the path to your Dockerfile if necessary
          push: true
          tags: |
            ansumansing/automation-project:${{ github.sha }}
